### ISSUE TITLE
1k xel bug

### ISSUE THREAD

**Issue by Litas-dev** [xel-software/xeline#1]
1 k + xel bug . 
. 
![untitled](https://user-images.githubusercontent.com/12777785/39405879-f12c4c94-4bad-11e8-9368-13baa074f2d2.jpg)

**Comment by cassidykeyser** [comment]
Can you circle the problem spot you are talking about? I read this over and over and am not spotting what you are talking about.

**Comment by RED29** [comment]
Look at the balance. You have a " . " and a " , " it seems that the software or the OS it running from thinks it is not thousand but 1 with some decimals.

**Comment by Litas-dev** [comment]
yes thats a point .
