### ISSUE TITLE
Can't access callback folder 

### ISSUE THREAD

**Issue by tieandsuit** [xel-software/xeline#9]
Callback folder is important for xeline, it's holds JS files that prints answer to xeline after task have been completed or failed. Need to have posobility to edit or create new callback files. 
![Screenshot_20190611_201113](https://user-images.githubusercontent.com/43476731/59295924-1a391b80-8c85-11e9-9966-41817525f893.jpg) 
1.0.9 realise for Windows. 

PS. I talking just about single file xeline "louncher" unsure how to name it. Cheers

**Comment by any1one** [comment]
This folder is located in `~/Library/Application\ Support/xeline/callbacks/`. 
On windows it should be under `AppData/Roaming/xeline` or something like that, to be confirmed.

**Comment by tieandsuit** [comment]
Need more easy access to it. Eventually need to find a way so it's possible to access from xeline it self.

**Comment by kyiss** [comment]
Does this will affect the use of miner?

**Comment by tieandsuit** [comment]
that's have nothing to do with a miner, callback files needed to show results of the given task. the difrent task needs a different callback, or simply to say a way to report what happened with the task in Xeline .

**Comment by kyiss** [comment]
![image](https://user-images.githubusercontent.com/37474134/59357214-02cd6180-8d5d-11e9-9804-f159ad9e7b7a.png)

Does this error have anything to do with xeline?

**Comment by tieandsuit** [comment]
No, this error is from miner is self. By this day asking community to help with miner, its need some optimization.
